{% set major_minor = "1.4" %}
{% set version = major_minor + ".64" %}

package:
  name: lighttpd
  version: {{ version }}

source:
  url: http://download.lighttpd.net/lighttpd/releases-{{ major_minor }}.x/lighttpd-{{ version }}.tar.gz
  sha256: 71e46403fb28371a06b23ef1cceffd75285140c6f62a879c777ee5af0d248801

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - pkg-config
    - libtool
    - perl  # Needed to run the tests
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - make
    - automake
    - autoconf
    - libtool
    - m4
  host:
    - zlib
    - bzip2
    - pcre
    - pcre2
    - krb5
    - openssl
    - libxml2
    - sqlite
    - libuuid
    - mysql
    - gnutls
    - openldap
    - bzip2
    - nettle
    - keyutils
  run:
    - bzip2
    - pcre2
    - krb5
    - openssl
    - libxml2
    - sqlite
    - libuuid
    - keyutils

test:
  files:
    - lighttpd.conf
  commands:
    - lighttpd -h
    - lighttpd -v
    - lighttpd -t -f lighttpd.conf

about:
  home: http://www.lighttpd.net/
  license: BSD-3-Clause
  license_file: COPYING
  summary: Light, fast web server
  description: |
    Lighttpd is rapidly redefining the efficiency of a webserver. It is
    designed and optimized for high performance environments. With a small
    memory footprint compared to other web-servers, effective management of
    the cpu-load, and an advanced feature set, lighttpd is the perfect
    solution for every server that is suffering load problems.
  doc_url: http://redmine.lighttpd.net/projects/lighttpd/wiki
  doc_source_url: http://redmine.lighttpd.net/projects/lighttpd/repository/revisions/master/show/doc
  dev_url: https://github.com/lighttpd

extra:
  recipe-maintainers:
    - sdvillal
    - notestaff
