#
# Inspired in the original defaults recipe at:
#   https://github.com/ContinuumIO/anaconda-recipes/tree/master/lighttpd
#
# This updates to newer versins, builds with bzip2 and pcre support and
# includes a more comprehensive example of MIME config.
#
# See also:
#  - https://redmine.lighttpd.net/projects/lighttpd/wiki/InstallFromSource
#  - https://redmine.lighttpd.net/projects/lighttpd/wiki/OptionalLibraries
#

{% set version = "1.4.49" %}
{% set build_number= "0" %}

package:
  name: lighttpd
  version: {{ version }}

source:
  fn: lighttpd-{{ version }}.tar.gz
  url: http://download.lighttpd.net/lighttpd/releases-1.4.x/lighttpd-{{ version }}.tar.gz
  sha256: 8b744baf9f29c386fff1a6d2e435491e726cb8d29cfdb1fe20ab782ee2fc2ac7

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - toolchain
    - pkg-config
    - libtool
    - zlib 1.2.11
    - bzip2 1.0.*
    - pcre 8.39*
    - krb5 1.14.*
    - openssl 1.0.*
    - libxml2 2.9.*
    - sqlite 3.13.*
    - libuuid
    - mysql
    - perl  # Needed to run the tests
  run:
    - zlib 1.2.11
    - bzip2 1.0.*
    - pcre 8.39*
    - krb5 1.14.*
    - openssl 1.0.*
    - libxml2 2.9.*
    - sqlite 3.13.*
    - libuuid

test:
  files:
    - lighttpd.conf
  commands:
    - lighttpd -h
    - lighttpd -v
    - lighttpd -t -f lighttpd.conf

about:
  home: http://www.lighttpd.net/
  license: BSD 3-Clause
  license_file: COPYING
  summary: Light, fast web server
  description: |
    Lighttpd is rapidly redefining the efficiency of a webserver. It is
    designed and optimized for high performance environments. With a small
    memory footprint compared to other web-servers, effective management of
    the cpu-load, and an advanced feature set, lighttpd is the perfect
    solution for every server that is suffering load problems.
  doc_url: http://redmine.lighttpd.net/projects/lighttpd/wiki
  doc_source_url: http://redmine.lighttpd.net/projects/lighttpd/repository/revisions/master/show/doc
  dev_url: https://github.com/lighttpd

extra:
  recipe-maintainers:
    - sdvillal
