travis:
  secure:
    BINSTAR_TOKEN: MnJYGeUEo4PQZNdmpyN6UYwWcN9Y0GOPJ2QvEgZsMplrz/lWhVeG6P6YU7Pjbqikw9I+GhxOTyK6Dt0bQnc/gdapnhhV75tnSF+6SeYUTh+mn2GZQ1v1gOx0Jv/4fb6nULNjRnZVNkb/pDNImlvqxKT3GGqZzp3EKs+gPo4R9ceoePm6hXeg+RneKMUyzTvLq0BdkhaX74ZQ6Kkra7h8egTiHOD8tU4ioPj8Q0QE09wCwaTlKUeGu+DZJkRxvYJi5SwfvUSaY7j0PaeGS0v6Pas+DwQu5usX3tLgz4sDfnfYngSFafnTenMjGonwFQBomeO7zlCTr8dnj56bKm1P8UZd5w+vaqW1v0Q2p1JP/u8r22hZUzgy5lptwNfU9ADMjhXJj4HtEpSK+kQmY50OgyyxTpL4Xtq9KBnSrJryg959J4+oNJy6QzWb+FODaDswdzqZDM5aEbcNZhfZQpzKUFnXx5lGFHcYGBVeWN+cJ8rcUFp21QanMMrWv++HPilI9EA+oYogS+H5T+5lKjxUbeL+aPZmLmbNqZ3o1VtWL5HHfiVTQNZoWCL+xY5ys+XOVy52joWNqhgwpRVGgsfsOEd8JkpEGOY/VuSi9gXIW9xWTg8n6OIt3LTfRzb+AoScMnAXil2Gn4lwzgTebtAgRI9pg7jdFwRHogHFwskLwXY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
